services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: medusa-starter
      POSTGRES_PASSWORD: medusa-password
      POSTGRES_DB: medusa-starter
    ports:
      - 5432:5432
    networks:
      - dokploy-network
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 1024M
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "medusa-starter"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - 6379:6379
    networks:
      - dokploy-network
    volumes:
      - cache-backend-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-server:
    build: medusa-starter-default
    ports:
      - 9000
    networks:
      - dokploy-network
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2048M
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - backend-server-data:/data
    environment:
      NODE_ENV: CI
      STORE_CORS: http://localhost:8000,https://dashboard.futuretools.app
      ADMIN_CORS: http://localhost:8000,http://localhost:9000,https://dashboard.futuretools.app,https://api.futuretools.app
      REDIS_URL: redis://redis:6379
      CACHE_REDIS_URL: redis://redis:6379
      EVENTS_REDIS_URL: redis://redis:6379
      WE_REDIS_URL: redis://redis:6379
      DATABASE_URL: postgres://medusa-starter:medusa-password@postgres/medusa-starter?ssl_mode=disable
      POSTGRES_URL: postgres://medusa-starter:medusa-password@postgres/medusa-starter?ssl_mode=disable
      MEDUSA_CREATE_ADMIN_USER: true
      MEDUSA_ADMIN_EMAIL: admin@medusa-test.com
      MEDUSA_ADMIN_PASSWORD: supersecret
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.medusa-api.rule=Host(`api.futuretools.app`)"
      - "traefik.http.routers.medusa-api.entrypoints=websecure"
      - "traefik.http.routers.medusa-api.tls.certResolver=letsencrypt"
      - "traefik.http.services.medusa-api.loadbalancer.server.port=9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

networks:
  dokploy-network:
    external: true

volumes:
  postgres-data:
  backend-server-data:
  cache-backend-data:
